### ISSUE TITLE
Property 'listen' does not exist on type 'Promise<INestApplication>'

### ISSUE THREAD

**Issue by cdiaz** [AngelMunoz/nesting-nuxt#1]
TSError: ⨯ Unable to compile TypeScript
src/server.ts (18,7): Property 'listen' does not exist on type 'Promise<INestApplication>'. (2339)

**Comment by AngelMunoz** [comment]
Hi, thanks for the issue, would you provide me more information? 
I have it currently running with the following versions and no problem so far:
- ts-node: 3.2.0
- typescript: 2.1.4
- nestjs/common@3.0.0
- nestjs/core@3.0.1
- nestjs/microservices@3.0.1
- nestjs/testing@3.0.0
- nestjs/websockets@3.0.0
- node 8

perhaps between  ts-node or typescript? also  my 
my type definitions (which come with nest) don't return a Promise<INestApplication> but a INestApplication Instead from `NestFactory#create`

**Comment by AngelMunoz** [comment]
hey @cdiaz  I think this issue is related to https://github.com/kamilmysliwiec/nest/issues/102 which involves either updating ts-node to version 3.2.0 or downgrade typescript to 2.3.4 while the fix gets to npm 😃
